---
title: "beetle_family_names"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{beetle_family_names}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

####################################################################
## Insect Invasions Pursuit @ SESYNC                              ##
## check the Coleoptera family names                              ##
## created by Rachael Blake    05/05/2020                         ##
####################################################################

```{r eval=FALSE}
library(tidyverse); library(readxl) ; library(taxize)

# read in the list of beetle families
floc <- "path/to/your/data/Copy of number of native species by beetle family in regions2.xlsx"
beetle_fams <- read_excel(floc, trim_ws = TRUE, col_types = "text" )
bfams_list <- beetle_fams$Family
```

### Run the bfams_list through the GBIF taxonomic cleaning process
```{r eval=FALSE}

beetle_accepted <- lapply(bfams_list, get_accepted_families)

# make dataframe
suppressMessages(
b_acc_df <- beetle_accepted %>%
            purrr::reduce(full_join) %>%
            select(-genus, -genuskey)
)
```

### Write out the file
```{r eval=FALSE}
readr::write_csv(b_acc_df, "path/to/your/data/Coleoptera_accepted_taxonomy.csv")
```
